With B as (
SELECT /*+ PARALLEL(B,$ORA_PARALLEL) */ LEGACY_CONTACT_ID AS LEGACY_CONTACT_ID FROM migration_10.uf_contact A
MINUS
SELECT /*+ PARALLEL (A,$ORA_PARALLEL) */ LEGACY_CONTACT_ID FROM migration_10.UF_CON_ROLES C)
SELECT DISTINCT STG.LEGACY_ACCOUNT_NO LEGACY_CUST_ID,STG.SOURCE_SYSTEM,B.LEGACY_CONTACT_ID,
CASE WHEN STG.LEGACY_ACCOUNT_NO  NOT IN 
(select ACCOUNT_NAME from APP_2.APP_SV_BILL_ADD_ELOC_SUCESS WHERE MODIFY_DTS IS NULL AND ACCOUNT_NAME IS NOT NULL)
AND STG.LEGACY_ACCOUNT_NO NOT IN (select ACCOUNT_NAME from APP_2.APP_SV_TAX_ADD_ELOC_SUCESS WHERE MODIFY_DTS IS NULL AND ACCOUNT_NAME IS NOT NULL) 
--OR (STG.LEGACY_ACCOUNT_NO NOT IN (SELECT LEGACY_CUST_ID FROM migration_10.UF_CUSTOMER))
THEN 'BILLING AND  TAX MISSES'
ELSE 'NEED TO CHECK' END AS  RCA
FROM migration_10.STG_COMP_FINAL STG INNER JOIN B 
ON STG.LEGACY_CONTACT_ID=B.LEGACY_CONTACT_ID
WHERE  STG.SOURCE_SYSTEM NOT IN ('CEN','WB','WT');

With B as (
SELECT /*+ PARALLEL(B,$ORA_PARALLEL) */ LEGACY_CONTACT_ID AS LEGACY_CONTACT_ID FROM migration_10.uf_contact A
MINUS
SELECT /*+ PARALLEL (A,$ORA_PARALLEL) */ LEGACY_CONTACT_ID FROM migration_10.UF_CON_ROLES C)
SELECT DISTINCT HIER.ROOT_ACCOUNT_NAME,
--STG.LEGACY_ACCOUNT_NO LEGACY_CUST_ID,STG.SOURCE_SYSTEM,B.LEGACY_CONTACT_ID,STG.UNI_ID,HIER.FINAL_SCHEMA,
CASE WHEN HIER.FINAL_SCHEMA ='ME' AND  STG.UNI_ID
IN (SELECT IDENTIFIER FROM migration_6.STG_SRC_SUBSCRIBER_LOB WHERE LEGACY_SITE_ID IS NULL) THEN 'SITES NULL'
WHEN HIER.FINAL_SCHEMA ='AV' AND  STG.UNI_ID
IN (SELECT IDENTIFIER FROM migration_8.STG_SRC_SUBSCRIBER_LOB WHERE LEGACY_SITE_ID IS NULL) THEN 'SITES NULL'
WHEN HIER.FINAL_SCHEMA ='BCV' AND  STG.UNI_ID
IN (SELECT IDENTIFIER FROM migration_9.STG_SRC_SUBSCRIBER_LOB WHERE LEGACY_SITE_ID IS NULL) THEN 'SITES NULL'

WHEN STG.UNI_ID NOT IN (select EPID from APP_2.APP_CLIPS_ADDRESS_ELOC_SUCESS WHERE MODIFY_DTS IS NULL AND EPID IS NOT NULL) THEN 'SITES MISSES IN CLIPS-383'
ELSE 'NEED TO CHECK' END AS RCA
FROM migration_10.STG_COMP_FINAL STG,B ,APP_2.CUST_HIERARCHY HIER
WHERE STG.LEGACY_CONTACT_ID=B.LEGACY_CONTACT_ID AND STG.LEGACY_ACCOUNT_NO=HIER.ACCOUNT_NAME
AND STG.SOURCE_SYSTEM  IN ('CEN','WB','WT');
