---541
WITH VQ_541 AS (
select DISTINCT b.LEGACY_CUST_ID, b.LEGACY_SITE_ID,A.SOURCE_SYSTEM,A.ADR_LINE_1,A.STATE_CODE,A.CITY,A.ZIPCODE
from migration_10.uf_address a , migration_10.uf_site b , migration_10.IC_541 c
where a.LEGACY_ADDRESS_ID = b.LEGACY_ADDR_ID
and b.LEGACY_CUST_ID = c.LEGACY_CUST_ID
and UPPER(a.city) = UPPER(c.city)
and UPPER(a.ADR_LINE_1) = UPPER(c.ADR_LINE_1)
and a.ZIPCODE = c.ZIPCODE
and NVL(a.UNIT_TYPE, 'XXX') = NVL(c.UNIT_TYPE, 'XXX')
and NVL(a.UNIT_value, 'XXX') = NVL(c.UNIT_VALUE, 'XXX')
and nvl(a.UNIT_TYPE_2, 'xxx') = nvl(c.UNIT_TYPE_2 , 'xxx')
and NVL(a.UNIT_value_2, 'XXX') = NVL(c.UNIT_VALUE_2, 'XXX')
and nvl(a.UNIT_TYPE_3, 'xxx') = nvl(c.UNIT_TYPE_3 , 'xxx')
and NVL(a.UNIT_value_3, 'XXX') = NVL(c.UNIT_VALUE_3, 'XXX')),

COL_LIST AS (

SELECT DISTINCT ADR_LINE_1,ADDRESS_TYPE,LISTAGG(COL_NAME,',') OVER (PARTITION BY ADR_LINE_1,ADDRESS_TYPE)  COL_LIST_DIFF_VALS
FROM (
SELECT ADR_LINE_1,ADDRESS_TYPE,COL_NAME
FROM (
SELECT ADR_LINE_1,ADDRESS_TYPE,COL_NAME, COL_VAL FROM (
SELECT ADR_LINE_1,ADDRESS_TYPE,LEGACY_ADDRESS_ID,POST_OFFICE_BOX, STREET_NAME, STREET_NUMBER, APARTMENT, LONGITUDE, LATITUDE, COUNTY, GEOCODE, BUSINESS_UNIT_ID,
CLLI_CODE, CENSUS_BLOCK, NVL(NAX_ID,'XXXX') NAX_ID, FRANCHISE_TAX_AREA, ATTN_TO, HOUSE_NUMBER_PREFIX, HOUSE_NUMBER_SUFFIX, STREET_PRE_DIRECTION, STREET_SUFFIX, STREET_POST_DIRECTION,
DIVISION, REGION, MARKET, SUB_MARKET, NVL(ELOC_LOCATION_ID,'XXXX') ELOC_LOCATION_ID, CRAN, TO_CHAR(ATHENA_ADDRESS_ID)  ATHENA_ADDRESS_ID, TO_CHAR(ATHENA_BUILDING_ID) ATHENA_BUILDING_ID, ACCESS_PROVIDER, CUID, ZIP_EXTENSION, RATE_CENTER
FROM migration_10.uf_address
--WHERE ADR_LINE_1='3810 PLAINFIELD RD'
)
UNPIVOT (COL_VAL FOR COL_NAME IN (LEGACY_ADDRESS_ID,POST_OFFICE_BOX, STREET_NAME, STREET_NUMBER, APARTMENT, LONGITUDE, LATITUDE, COUNTY, GEOCODE, BUSINESS_UNIT_ID,
CLLI_CODE, CENSUS_BLOCK, NAX_ID, FRANCHISE_TAX_AREA, ATTN_TO, HOUSE_NUMBER_PREFIX, HOUSE_NUMBER_SUFFIX, STREET_PRE_DIRECTION, STREET_SUFFIX, STREET_POST_DIRECTION,
DIVISION, REGION, MARKET, SUB_MARKET, ELOC_LOCATION_ID, CRAN, ATHENA_ADDRESS_ID , ATHENA_BUILDING_ID, ACCESS_PROVIDER, CUID, ZIP_EXTENSION, RATE_CENTER)

)

)
GROUP BY ADR_LINE_1,ADDRESS_TYPE,COL_NAME HAVING COUNT (DISTINCT COL_VAL)>1

)
)


SELECT VQ.LEGACY_CUST_ID,VQ.LEGACY_SITE_ID,
LISTS.ADDRESS_TYPE,LISTS.COL_LIST_DIFF_VALS ,
STD_LINE1,
CASE WHEN 
COUNT(*) OVER (PARTITION BY STD_LINE1,STD_STATE,STD_CITY,STD_ZIP) >1 
THEN 'ADDRESS DUPS IN SRC' ELSE 'NEED TO CHECK -MIGHT BE DUPS B/W CLIPS AND CSG' END AS RCA
FROM VQ_541 VQ LEFT JOIN APP_2.APP_CLIPS_ADDRESS_ELOC_SUCESS CLIPS
ON VQ.LEGACY_CUST_ID=CLIPS.accountnumber AND VQ.LEGACY_SITE_ID=CLIPS.locationid
LEFT JOIN COL_LIST LISTS ON CLIPS.STD_LINE1=LISTS.ADR_LINE_1 
WHERE CLIPS.MODIFY_DTS IS NULL  AND VQ.SOURCE_SYSTEM='CLIPS'
UNION ALL

SELECT VQ.LEGACY_CUST_ID,VQ.LEGACY_SITE_ID,
LISTS.ADDRESS_TYPE,LISTS.COL_LIST_DIFF_VALS,
STD_LINE1,
CASE WHEN 
COUNT(*) OVER (PARTITION BY STD_LINE1,STD_STATE,STD_CITY,STD_ZIP) >1
THEN 'ADDRESS DUPS IN SRC' ELSE 'NEED TO CHECK -MIGHT BE DUPS B/W CLIPS AND CSG' END AS RCA
FROM VQ_541 VQ LEFT JOIN 
(       select distinct ROOT_ACCOUNT,NVL(SBB.HSE_KEY_SBB,CSG.STD_LEGACY_LOCATIONID) LEGACY_ADDRESS_ID,
        STD_LINE1,STD_STATE,STD_CITY,STD_ZIP
        FROM APP_2.APP_CSG_SITE_ADDR_GLX_SUCESS CSG
        LEFT OUTER JOIN base_2.CSG_SBB_BASE SBB
        ON CSG.AAN = SBB.SUB_ACCT_NO_SBB
        WHERE CSG.MODIFY_DTS IS NULL 
    )CSG
ON  VQ.LEGACY_CUST_ID=CSG.ROOT_ACCOUNT  AND 
VQ.LEGACY_SITE_ID=CSG.LEGACY_ADDRESS_ID
LEFT JOIN COL_LIST LISTS ON CSG.STD_LINE1=LISTS.ADR_LINE_1 
WHERE VQ.SOURCE_SYSTEM='CSG';
