WITH CUST_312 AS (
select legacy_cust_id,legacy_sub_no,LEGACY_PRODUCT_OFFER,LEGACY_SITE_ID from migration_10.uf_subscriber where legacy_sub_no in (select legacy_sub_no from (
SELECT /*+ PARALLEL(B,$ORA_PARALLEL) */ distinct LEGACY_SUB_NO,LEGACY_SITE_ID 
FROM migration_10.UF_SUBSCRIBER A, migration_10.CONV_TT T 
WHERE  T.TRANS_GROUP='TRANS_EPC_OFFER' AND T.INPUT_VAL1=A.LEGACY_PRODUCT_OFFER AND T.INPUT_VAL2='S' AND T.OUTPUT_VAL6 not in ('EVC')
MINUS 
SELECT /*+ PARALLEL (A,$ORA_PARALLEL) */ LEGACY_ENTITY_ID, LEGACY_SITE_ID FROM migration_10.UF_CON_ROLES C 
WHERE RECORD_LEVEL = 'S' )))

 

SELECT 
legacy_cust_id,legacy_sub_no,LEGACY_PRODUCT_OFFER,LEGACY_SITE_ID ,CASE WHEN LEGACY_SITE_ID IS NULL THEN 'SITES NULL' 
WHEN LEGACY_PRODUCT_OFFER ='Site Access'  
AND legacy_sub_no NOT IN (SELECT INDEP_SUB_ID FROM migration_10.UF_SUB_ASSOCIATION UNION ALL SELECT DEP_SUB_ID FROM migration_10.UF_SUB_ASSOCIATION)
THEN 'NO ASSOCIATION FOR SITE ACCESS'
WHEN LEGACY_SITE_ID NOT IN (select LOCATIONID from APP_2.APP_CLIPS_ADDRESS_ELOC_SUCESS WHERE MODIFY_DTS IS NULL AND LOCATIONID IS NOT NULL)
THEN 'SITE MISSES IN CLIPS'
WHEN legacy_sub_no IN (SELECT LEGACY_ENTITY_ID FROM migration_10.UF_CON_ROLES)
THEN 'SUBNO IS PRESENT IN CONROLES ,ITS DUE TO SUBNO HAVING ONE NULL AND VALID SITE'
ELSE 'NEED TO CHECK' END AS RCA
FROM CUST_312;
